re-importing all revisions of SVN version (e.g. introducing customizable authentication) adding module SSL for single-step action for configuring certificate/key file of LDAP server

diff --git a/slapd-config b/slapd-config
--- a/slapd-config
+++ b/slapd-config
@@ -21,6 +21,27 @@
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 #
 
+# use SASL/EXTERNAL authentication by default
+AUTHENTICATION="${AUTHENTICATION:--Q -H ldapi:/// -Y EXTERNAL}"
+
+
+# detect base64 encoder/decoder
+if which base64 &>/dev/null; then
+	B64ENC="base64"
+	B64DEC="base64 -d"
+elif which openssl &>/dev/null; then
+	B64ENC="openssl base64"
+	B64DEC="openssl base64 -d"
+elif which recode &>/dev/null; then
+	B64ENC="recode ..base64"
+	B64DEC="recode base64.."
+else
+	B64ENC="echo 'missing base64 encoder' >&2 && exit 5"
+	B64DEC="echo 'missing base64 decoder' >&2 && exit 5"
+fi
+
+
+
 findEntries()
 {
 	if [ "${1}" = "-dn" ]
@@ -36,7 +57,7 @@ findEntries()
 
 	shift
 
-	ldapsearch -Q -LLL -H ldapi:/// -Y EXTERNAL -b "$basedn" "$query" "$@" | sed -ne '/^ *$/!p' | sed -ne '1h;1!H;${;x;s/\n //g;p;}'
+	ldapsearch $AUTHENTICATION -LLL -b "$basedn" "$query" "$@" | sed -ne '/^ *$/!p' | sed -ne '1h;1!H;${;x;s/\n //g;p;}'
 }
 
 DBName2DN()
@@ -46,7 +67,8 @@ DBName2DN()
 		[ "${1}" = "$name" -o "${1}" = "${name#*\}}" ] && { echo $dn; return 0; }
 	done
 
-	return 1
+	echo "invalid database: ${1}" >&2
+	exit 1
 }
 
 DBDN2Name()
@@ -60,13 +82,23 @@ values2LDIF()
 	values=
 	i=0
 
-	while read l; do
+	while read line; do
+		# insert line break
 		[ $i -eq 0 ] || values="$values\n"
-		values="$values${1}: {$i}${l}"
+
+		# add numeric indices to lines of values unless disabled
+		[ "${2}" = "nonumbers" ] || line="{$i}${line}"
+
+		# base64-encode line if required
+		echo -n "$line" | awk '/^[\x01-\x09\x0B\x0C\x0E-\x1F\x21-\x39\x3B\x3D-\x7F][\x01-\x09\x0B\x0C\x0E-\x7F]*$/ {print "valid"}' | grep valid &>/dev/null || {
+			line="$(echo -n "$line" | $B64ENC)"
+		}
+
+		values="$values${1}: ${line}"
 		i=$((i+1))
 	done
 
-	{ [ $i -lt 2 ] && sed 's/^\([^:]\+: \){0}/\1/' <<<"$values" || echo "$values"; } | sed 's/\\n/\n/g' | sed -n ':p;s/\([^\n]\{78\}\)\([^\n]\)/\1\n \2/;tp;p'
+	{ [ $i -lt 2 -a "${2}" != "nonumbers" ] && sed 's/^\([^:]\+: \){0}/\1/' <<<"$values" || echo "$values"; } | sed 's/\\n/\n/g' | sed -n ':p;s/\([^\n]\{78\}\)\([^\n]\)/\1\n \2/;tp;p'
 }
 
 listEntries()
@@ -76,7 +108,7 @@ listEntries()
 
 	shift 2
 
-	findEntries -dn "${dn}" "objectClass=*" dn -s "$scope" "$@" | sed -n '/^ *$/!s/[^:]*: //p'
+	findEntries -dn "${dn}" "objectClass=*" dn -s "$scope" "$@" | sed -n '/^ *$/!s/[^:]*::? ?//p'
 }
 
 showEntry()
@@ -93,19 +125,33 @@ readAttribute()
 	dn="${1}"
 	attr="${2}"
 
-	findEntries -dn "$dn" "$attr=*" "$attr" -s base | sed -n "/^$attr: /!d;s/^$attr: \({\(-\?[0-9][0-9]*\)}\)\?//;p"
+	findEntries -dn "$dn" "$attr=*" "$attr" -s base | sed -n '
+/^'"$attr"':/!d
+s/^'"$attr"': *\({\(-\?[0-9][0-9]*\)}\)\?/=/
+s/^'"$attr"':: */!/
+p' | while read line; do
+		case "${line:0:1}" in
+			"=")
+				echo "${line:1}"
+				;;
+			'!')
+				echo -n "${line:1}" | $B64DEC
+				;;
+		esac
+	done
 }
 
 writeAttribute()
 {
 	dn="${1}"
 	attr="${2}"
+	[ "${3}" = "nonumbers" ] && mode=nonumbers || mode=
 
-	ldapmodify -Q -H ldapi:/// -Y EXTERNAL <<EOT
+	ldapmodify $AUTHENTICATION <<EOT
 dn: $dn
 changetype: modify
 replace: $attr
-`values2LDIF "$attr"`
+$(values2LDIF "$attr" $mode)
 -
 EOT
 }
@@ -120,14 +166,14 @@ insertAttributeLine()
 	[ $idx -lt 1 ] && idx=1
 
 	{
-		readAttribute "$db" "$attr" | {
-			if [ $idx -le `readAttribute "$db" "$attr" | wc -l` ]; then
+		readAttribute "$dn" "$attr" | {
+			if [ $idx -le $(readAttribute "$dn" "$attr" | wc -l) ]; then
 				sed "${idx}i${rule}"
 			else
 				sed -n "p;\$i${rule}"
 			fi
 		}
-	} | writeAttribute "$db" "$attr"
+	} | writeAttribute "$dn" "$attr" "${5}"
 }
 
 deleteAttributeLine()
@@ -206,8 +252,9 @@ schemaFileToLDIF()
 	aidx=0
 	oidx=0
 
-	sed -e '/^#/d;/^ *$/d' | sed -ne '1h;1!H;${;x;s/[ \t]\+/ /g;s/ \?\n / /g;p;}' | sort | while read rule; do
-		case `echo ${rule%% *} | tr "A-Z" "a-z"` in
+	sed -e '/^#/d;/^ *$/d' | sed -ne '1h;1!H;${;x;s/[ \t]\+/ /g;s/ \?\n / /g;p;}' | while read rule; do
+		ruletype="${rule%% *}"
+		case "${ruletype,,}" in
 			attributetype)
 				[ $aidx -eq 0 ] || echo -n "\n"
 				echo -n "olcAttributeTypes: {$aidx}${rule#* }"
@@ -233,7 +280,7 @@ writeSchema()
 	if [ $? -eq 0 ]; then
 		dn="`schema2DN "${1}"`"
 
-		ldapmodify -Q -H ldapi:/// -Y EXTERNAL <<-EOT
+		ldapmodify $AUTHENTICATION <<-EOT
 dn: ${dn}
 changetype: modify
 replace: olcAttributeTypes
@@ -246,7 +293,7 @@ replace: olcObjectClasses
 	else
 		cn="`schema2CN "${1}" y`"
 
-		ldapadd -Q -H ldapi:/// -Y EXTERNAL <<-EOT
+		ldapadd $AUTHENTICATION <<-EOT
 dn: cn=${cn},cn=schema,cn=config
 objectClass: olcSchemaConfig
 cn: ${cn}
@@ -262,14 +309,14 @@ deleteSchema()
 	idx="${dn#*{}"
 	idx="${idx%%\}*}"
 
-	ldapdelete -Q -H ldapi:/// -Y EXTERNAL "${dn}" || { echo "failed to delete schema ${dn}" >&2; exit 2; }
+	ldapdelete $AUTHENTICATION "${dn}" || { echo "failed to delete schema ${dn}" >&2; exit 2; }
 
 	while testSchema "$((idx+1))"; do
 		olddn="`schema2DN "$((idx+1))"`"
 		newcn="`DN2Schema "${olddn}"`"
 		newcn="{$idx}$newcn"
 
-		ldapmodify -Q -H ldapi:/// -Y EXTERNAL <<-EOT
+		ldapmodify $AUTHENTICATION <<-EOT
 dn: ${olddn}
 changetype: modrdn
 newrdn: cn=${newcn}
@@ -304,43 +351,70 @@ listDatabases()
 	done
 }
 
-readAccessRulesOfDatabase()
+writeSslCertificate()
 {
-	db="`DBName2DN "${1}"`" || { echo "invalid database: ${1}" >&2; return 1; }
-	readAttribute "$db" olcAccess
-}
+	certFilename="${1}"
+	keyFilename="${2}"
+	caFilename="${3}"
 
-writeAccessRulesOfDatabase()
-{
-	db="`DBName2DN "${1}"`" || { echo "invalid database: ${1}" >&2; return 1; }
-	writeAttribute "$db" olcAccess
-	return $?
-cat | ldapmodify -Q -H ldapi:/// -Y EXTERNAL <<EOT
-dn: $db
+	[ -f "$certFilename" ] || { echo "missing certificate file: $certFilename" >&2; exit 1; }
+	[ -f "$keyFilename" ] || { echo "missing key file: $keyFilename" >&2; exit 1; }
+
+	if [ -n "$caFilename" ]
+	then
+		[ -f "$caFilename" ] || { echo "missing CA certificate file: $caFilename" >&2; exit 1; }
+
+		echo "setting up CA certificate file" >&2
+		ldapmodify $AUTHENTICATION <<-EOT
+dn: cn=config
 changetype: modify
-replace: olcAccess
-`values2LDIF olcAccess`
+replace: olcTLSCACertificateFile
+`values2LDIF olcTLSCACertificateFile <<<"$caFilename"`
 -
-EOT
+		EOT
+	fi
+
+	echo "setting up certificate/key files" >&2
+	ldapmodify $AUTHENTICATION <<-EOT
+dn: cn=config
+changetype: modify
+replace: olcTLSCertificateFile
+`values2LDIF olcTLSCertificateFile <<<"$certFilename"`
+-
+replace: olcTLSCertificateKeyFile
+`values2LDIF olcTLSCertificateKeyFile <<<"$keyFilename"`
+-
+	EOT
 }
 
-insertAccessRuleOfDatabase()
+deleteSslCertificate()
 {
-	db="`DBName2DN "${1}"`" || { echo "invalid database: ${1}" >&2; return 1; }
-	insertAttributeLine "${db}" olcAccess "${2}" "${3}"
+	if [ -n "$(readAttribute "cn=config" "olcTLSCertificateFile")" ]
+	then
+		echo "dropping certificate/key file" >&2
+		ldapmodify $AUTHENTICATION <<-EOT
+dn: cn=config
+changetype: modify
+delete: olcTLSCertificateFile
+-
+delete: olcTLSCertificateKeyFile
+-
+		EOT
+	fi
+
+	if [ -n "$(readAttribute "cn=config" "olcTLSCACertificateFile")" ]
+	then
+		echo "dropping CA certificate file" >&2
+		ldapmodify $AUTHENTICATION <<-EOT
+dn: cn=config
+changetype: modify
+delete: olcTLSCACertificateFile
+-
+		EOT
+	fi
 }
 
-deleteAccessRuleOfDatabase()
-{
-	db="`DBName2DN "${1}"`" || { echo "invalid database: ${1}" >&2; return 1; }
-	deleteAttributeLine "${db}" olcAccess "${2}"
-}
 
-showDatabase()
-{
-	db="`DBName2DN "${ARG}"`" || { echo "invalid database: ${1}" >&2; exit 1; }
-	findEntries -dn "$db"
-}
 
 usage()
 {
@@ -390,7 +464,7 @@ case "$MODULE" in
 
 	-h|--help|help)
 		usage <<-EOT
-available modules are: db raw schema
+available modules are: db raw schema ssl
 
 module-specific help is available with:
 
@@ -421,15 +495,15 @@ actions are:
 				readAttribute "$@"
 				;;
 			write)
-				[ $# -lt 2 ] && usage <<<"usage: $APPNAME raw write <DN> <attr>\n       (providing value lines on stdin)\n"
+				[ $# -lt 2 ] && usage <<<"usage: $APPNAME raw write <DN> <attr> [ nonumbers ]\n       (providing value lines on stdin)\n"
 				writeAttribute "$@"
 				;;
 			insert)
-				[ $# -lt 4 ] && usage <<<"usage: $APPNAME raw insert <DN> <attr> <linenum> \"<value>\"\n"
+				[ $# -lt 4 ] && usage <<<"usage: $APPNAME raw insert <DN> <attr> <linenum> \"<value>\" [ nonumbers ]\n"
 				insertAttributeLine "$@"
 				;;
 			delete)
-				[ $# -lt 3 ] && usage <<<"usage: $APPNAME raw delete <DN> <attr> <linenum>\n"
+				[ $# -lt 3 ] && usage <<<"usage: $APPNAME raw delete <DN> <attr> <linenum> [ nonumbers ]\n"
 				deleteAttributeLine "$@"
 				;;
 			list)
@@ -498,6 +572,10 @@ actions are:
   list          list name, suffix and DN of every DB containing LDAP thread
   list-all      list name and DN of every DB (incl. config databases etc.)
   show          provide properties of a single DB selected in parameter
+  read          read attribute from configuration of selected DB
+  write         write attribute in configuration of selected DB
+  insert        insert value line before selected one in attribute of DB
+  delete        remove selected value line from attribute of DB
   read-access   read access rules from DB selected in parameter
   write-access  write access rules to DB selected in parameter (rules on stdin)
   insert-access insert single access rule in set of rules of selected DB
@@ -513,23 +591,69 @@ actions are:
 				;;
 			show)
 				[ $# -lt 1 ] && usage <<<"usage: $APPNAME db show <dbname>\n"
-				showDatabase "$@"
+				findEntries -dn "$(DBName2DN "${1}")"
+				;;
+			read)
+				[ $# -lt 2 ] && usage <<<"usage: $APPNAME db read <dbname> <attr>\n"
+				readAttribute "$(DBName2DN "${1}")" "${2}"
+				;;
+			write)
+				[ $# -lt 2 ] && usage <<<"usage: $APPNAME db write <dbname> <attr> [ nonumbers ]\n       (providing value lines on stdin)\n"
+				writeAttribute "$(DBName2DN "${1}")" "${2}" ${3}
+				;;
+			insert)
+				[ $# -lt 4 ] && usage <<<"usage: $APPNAME db insert <dbname> <attr> <linenum> \"<value>\" [ nonumbers ]\n"
+				insertAttributeLine "$(DBName2DN "${1}")" "${2}" "${3}" "${4}" ${5}
+				;;
+			delete)
+				[ $# -lt 3 ] && usage <<<"usage: $APPNAME db delete <dbname> <attr> <linenum> [ nonumbers ]\n"
+				deleteAttributeLine "$(DBName2DN "${1}")" "${2}" "${3}" ${4}
 				;;
 			read-access)
 				[ $# -lt 1 ] && usage <<<"usage: $APPNAME db read-access <dbname>\n"
-				readAccessRulesOfDatabase "$@"
+				readAttribute "$(DBName2DN "${1}")" olcAccess
 				;;
 			write-access)
 				[ $# -lt 1 ] && usage <<<"usage: $APPNAME db write-access <dbname>\n"
-				writeAccessRulesOfDatabase "$@"
+				writeAttribute "$(DBName2DN "${1}")" olcAccess
 				;;
 			insert-access)
 				[ $# -lt 3 ] && usage <<<"usage: $APPNAME db insert-access <dbname> <ruleindex> \"<rule>\"\n"
-				insertAccessRuleOfDatabase "$@"
+				insertAttributeLine "$(DBName2DN "${1}")" olcAccess "${2}" "${3}"
 				;;
 			delete-access)
 				[ $# -lt 2 ] && usage <<<"usage: $APPNAME db delete-access <dbname> <ruleindex>\n"
-				deleteAccessRuleOfDatabase "$@"
+				deleteAttributeLine "$(DBName2DN "${1}")" olcAccess "${2}"
+				;;
+			*)
+				badaction
+				;;
+		esac
+		;;
+
+	ssl)
+		case "$ACTION" in
+			help)
+				usage <<-EOT
+module: ssl
+
+actions are:
+
+  write    update SSL/TLS certificate and key of server
+  delete   delete any existing SSL/TLS certificate of server
+  show     display configured SSL/TLS certificate and key of server
+
+				EOT
+				;;
+			write)
+				[ $# -lt 2 ] && usage <<<"usage: $APPNAME ssl write <cert-filename> <key-filename>\n"
+				writeSslCertificate "$@"
+				;;
+			delete)
+				deleteSslCertificate
+				;;
+			show)
+				findEntries -dn "cn=config" | awk '/^olcTLS/ {print $0}'
 				;;
 			*)
 				badaction
